<?php
return array (
  'mxcms' => 
  array (
    's1' => 
    array (
      'logo1' => '/template/mxone/mxstatic/image/logo.png',
        'yjlogokg' => '0',
      'yjlogo1' => '/template/mxone/mxstatic/image/yjlogo.png',
      'logo2' => '/template/mxone/mxstatic/picture/logo.png',
	  'logo3' => '/template/mxone/mxstatic/picture/logo.png',
      'pic' => '/template/mxone/mxstatic/image/loading.gif',
       'pic1' => '/template/mxone/mxstatic/image/loading.gif',
      'gg' => 'mxone',
      'searchwd' => '搜索电影、电视剧、综艺、动漫',
      'sm' => '本站所有内容均来自互联网分享站点所提供的公开引用资源，未提供资源上传、存储服务。',
    ),
    's2' => 
    array (
      'wz0' => '1',
      'wz01' => '1',
      'wz2' => '1',
      'wz3' => '0',
      'wz4' => '0',
      'wz5' => '0',
      'user' => '1',
      'shoucang' => '1',
      'app' => '1',
      'hot' => '1',
      'mxvodid' => '23',
      'new' => '1',
      'logtype' => '1,2,3,4',
      'slidenum' => '8',
      'slidetj' => '5',
       'hotlevel' => '1',
        'hotall' => 'all',
      'topic' => '1',
      'slidediy1' => '0',
      'slidediy1name' => '',
      'slidediy1url' => '',
      'slidediy1pic' => '',
      'slidediy2' => '0',
      'slidediy2name' => '',
      'slidediy2url' => '',
      'slidediy2pic' => '',
      'slidediy3' => '0',
      'slidediy3name' => '',
      'slidediy3url' => '',
      'slidediy3pic' => '',
      'slidediy4' => '0',
      'slidediy4name' => '',
      'slidediy4url' => '',
      'slidediy4pic' => '',
      'slidediy5' => '0',
      'slidediy5name' => '',
      'slidediy5url' => '',
      'slidediy5pic' => '',
      'diy1' => '0',
      'diy1name' => '',
      'diy1url' => '',
       'diy1icon' => 'iconfont icon-zidingyiquyu',
      'diy2' => '0',
      'diy2name' => '',
      'diy2url' => '',
        'diy2icon' => 'iconfont icon-zidingyiquyu',
      'diy3' => '0',
      'diy3name' => '',
      'diy3url' => '',
      'diy3icon' => 'iconfont icon-zidingyiquyu',
      'slide' => '1',
      'liuyan' => '1',
      'yjqh' => '1',
      'yxjcd' => '1',
      'dbdh' => '1',
      'about' => '1',
      'dbtop' => '1',
      'web1' => 'menell.taobao.com',
      'web2' => 'menell.taobao.com',
      'web3' => 'menell.taobao.com',
      'web4' => 'menell.taobao.com',
      'web5' => 'menell.taobao.com',
      'tc' => '1',
      'tc_noti' => '<p>欢迎使用Mxonex模板</p>
<p>本次更新内容</p>
<p>主题后台,分集剧情,明星页,相关话题,修复BUG</p>
<p>感谢你的支持,Menell.taobao.com</p>',
      'bftip' => '1',
        'bftips1' => '不要轻易相信视频中的任何广告，谨防上当受骗',
        'bftips2' => '如遇视频无法播放或加载速度慢，可尝试切换播放节点或者切换解析',
      'app_url' => '',
      'app_url2' => '',
      'miniplay' => '0',
      'tzzt' => '0',
    'daohangid' => 'parent',
    'doubanlj' => '1',
     'sydh' => '0',
      'sydhicon' => 'icon-all',
       'sydhall' => '',
        'comment' => '1',
         'detailen' => '1',
          'listlevel' => '',
          'xght' => '1',
           'pcdhicon' => '0',
           'num1' => '1',
      'num2' => '2',
      'num3' => '3',
      'num4' => '4',
      'num5' => '5',
      'num6' => '6',
      'num7' => '7',
      'icon1' => 'icon-cate-dy',
      'icon2' => 'icon-cate-ds',
      'icon3' => 'icon-cate-zy',
      'icon4' => 'icon-cate-dm',
      'icon5' => 'iconfont icon-zixun2',
      'icon6' => '',
      'icon7' => '',
      'iconmr' => 'iconfont icon-kongbaiwendang',
      'todaygx' => '1',
       'todaycss' => '#FF0000',
       'hoticon' => '0',
       'hoticoncss' => '#FF0000',
        'lbiconkg' => '0',
       'lbnum1' => '1',
      'lbnum2' => '2',
      'lbnum3' => '3',
      'lbnum4' => '4',
      'lbnum5' => '5',
      'lbnum6' => '6',
      'lbnum7' => '7',
       'lbnum8' => '8',
      'lbicon1' => 'icon-cate-dy',
      'lbicon2' => 'icon-cate-ds',
      'lbicon3' => 'icon-cate-zy',
      'lbicon4' => 'icon-cate-dm',
      'lbicon5' => 'iconfont icon-zixun2',
      'lbicon6' => '',
      'lbicon7' => '',
        'lbicon8' => '',
      'lbiconmr' => 'iconfont icon-kongbaiwendang',
       'lbiconcss' => '#FF0000',
       'newids' => 'parent',
        'pcgddh' => '1',
         'gddhbg' => '0',
         'gddhbgdm' => '',
        'listphb' => '1',
         'listphbname' => '月榜',
         'listphbtj' => '',
         'listphbby' => 'hits_month',
         'searchhoticon' => '1',
          'mryj' => '0',
           'indextopic' => '1',
          'indextopicnum' => '4',
           'indexart' => '1',
            'indexartid' => '5',
            'indexartnum' => '6',
             'wapsydh' => '1',
             'tagkg' => '1',
             'yxjdiy' => '0',
             'iconztys' => '',
             'cdbjys' => '',
             'iconbjys' => '',
             'iconbjglys' => '',
               'qzslt' => '0',
                'zhiboym' => '1',
                'diyliveicon' => 'iconfont icon-zhibo',
                'newicon' => '0',
                'newiconcss' => '#FF0000',
                  'sytopicicon' => '0',
                'sytopiciconcss' => '#FF0000;',
                  'syzixunicon' => '0',
                'syzixuniconcss' => '#FF0000',
                'diysearchhoticon' => 'icon-cupfox phb', 
    ),
    's3' => 
    array (
     'ad1' => '0',
      'aad1' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位01</h3></div>',
       'ad2' => '0',
      'aad2' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位02</h3></div>',
       'ad3' => '0',
      'aad3' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-top: 20px;"> <h3 style="text-align: center;">广告位03</h3></div>',
       'ad4' => '0',
      'aad4' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位04</h3></div>',
      'adqj' => '0',
      'aadqj' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位05</h3></div>',
       'addb' => '0',
       'aaddb' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位06</h3></div>',
        'pcad1' => '0',
      'pcaad1' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位01</h3></div>',
       'pcad2' => '0',
      'pcaad2' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位02</h3></div>',
       'pcad3' => '0',
      'pcaad3' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-top: 20px;"> <h3 style="text-align: center;">广告位03</h3></div>',
       'pcad4' => '0',
      'pcaad4' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位04</h3></div>',
        'wapad1' => '0',
      'wapaad1' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位01</h3></div>',
       'wapad2' => '0',
      'wapaad2' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位02</h3></div>',
       'wapad3' => '0',
      'wapaad3' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-top: 20px;"> <h3 style="text-align: center;">广告位03</h3></div>',
       'wapad4' => '0',
      'wapaad4' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位04</h3></div>',
    ),
    's4' => 
    array (
     'shier' => '0',
      'pbtips' => '你知道的太多了',
      'ctrl' => '0',
      'right' => '0',
       'mode' => '0',
       'tbdm' => '1',
       'tbdmtips' => '<meta name="referrer" content="always"> 
<meta name="referrer" content="no-referrer" />',
        'dbdm' => '1',
         'dbdmtips' => '统计代码',
         'stylediy' => '0',
         'stylecss' => ''
    ),
     's5' => 
    array (
     'wapdaohangid' => 'parent',
      'num1' => '1',
      'num2' => '2',
      'num3' => '3',
      'num4' => '4',
      'num5' => '5',
      'num6' => '6',
      'num7' => '7',
      'num8' => '8',
      'num9' => '9',
      'num10' => '10',
      'icon1' => 'icon-cate-dy',
      'icon2' => 'icon-cate-ds',
      'icon3' => 'icon-cate-zy',
      'icon4' => 'icon-cate-dm',
      'icon5' => 'iconfont icon-zixun2',
      'icon6' => '',
      'icon7' => '',
      'icon8' => '',
      'icon9' => '',
      'icon10' => '',
      'iconmr' => 'iconfont icon-kongbaiwendang',
      'diy1' => '0',
      'diy1name' => '',
      'diy1url' => '',
       'diy1icon' => 'iconfont icon-zidingyiquyu',
      'diy2' => '0',
      'diy2name' => '',
      'diy2url' => '',
       'diy2icon' => 'iconfont icon-zidingyiquyu'
    ),
     's6' => 
    array (
     'wapdaohangid' => 'parent',
      'num1' => '1',
      'num2' => '2',
      'num3' => '3',
      'num4' => '4',
      'num5' => '5',
      'icon1' => 'icon-cate-dy',
      'icon2' => 'icon-cate-ds',
      'icon3' => 'icon-cate-zy',
      'icon4' => 'icon-cate-dm',
      'icon5' => 'iconfont icon-zixun2',
      'iconmr' => 'iconfont icon-kongbaiwendang',
      'diy1' => '0',
      'diy1name' => '',
      'diy1url' => '',
       'diy1icon' => 'iconfont icon-zidingyiquyu',
       'diy2' => '0',
      'diy2name' => '',
      'diy2url' => '',
       'diy2icon' => 'iconfont icon-zidingyiquyu'
    ),
    's7' => 
    array (
     'hotpxb' => '1',
      'hotlevel' => '',
      'hotnum' => '10',
      'zztjb' => '1',
      'zztjlevel' => 'all',
      'zztjnum' => '10',
      'diytopids' => '1,2,3,4',
      'diytopidslevel' => '',
      'diytopidsnum' => '10',
      'num1' => '1',
      'num2' => '2',
      'num3' => '3',
      'num4' => '4',
      'num5' => '5',
      'num6' => '6',
      'icon1' => 'icon-cate-dy',
      'icon2' => 'icon-cate-ds',
      'icon3' => 'icon-cate-zy',
      'icon4' => 'icon-cate-dm',
      'icon5' => '',
      'icon6' => '',
      'iconmr' => 'iconfont icon-zhibo',
    ),
  ),
);



